name: base-pkg-image

description: |
  Build (and push) the base-pkg image

on:
  workflow_dispatch:
    inputs:
      cargo-pgrx-version:
        required: false
        type: string
        default: "0.14.1"
        description: |
          version of cargo-pgrx to download (inside image build)

concurrency:
  group: pg_idkit # Project-wide
  cancel-in-progress: true

permissions:
  contents: none

jobs:
  build-and-push-builder-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Log in to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build base-pkg image
        env:
          BUILDER_IMAGE_ARG_CARGO_PGRX_VERSION: ${{ inputs.cargo-pgrx-version }}
        run: |
          just build-base-pkg-image

      - name: Push base-pkg image
        run: |
          just push-base-pkg-image
