name: rpm

on:
  push:
    tags:
      - v[0-9]+\.[0-9]+\.[0-9]+

jobs:
  build:
    strategy:
      matrix:
        config:
          - gh:
              runner: ubuntu-latest
            rpm:
              arch: x86_64
            pgrx:
              version: pg15
    runs-on: ${{ matrix.config.gh.runner }}
    env:
      CARGO_PROFILE: "ci"
      PGRX_PG_VERSION: ${{ matrix.config.pgrx.version }}
      RPM_ARCH: ${{ matrix.config.rpm.arch }}

    steps:
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - name: Cache default PGRX_HOME
        uses: actions/cache@v2
        continue-on-error: false
        with:
          path: |
            /home/runner/.pgrx
          key: pg_idkit-pkg-rpm-pgrx-${{ matrix.config.rpm.arch }}-${{ runner.os }}

      - name: Install Rust deps
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall,cargo-get,just,cargo-generate-rpm,cargo-pgrx@0.11.0

      - name: Initialize cargo-pgrx
        run: |
          [[ -d /home/runner/.pgrx ]] || cargo pgrx init

      - name: Build RPM
        run: just package build-rpm

      - name: Get RPM output path
        id: rpm-output
        run: |
          echo path=$(just print-rpm-output-path) >> $GITHUB_OUTPUT
          echo filename=$(just print-rpm-output-file-name) >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.rpm-output.outputs.filename }}
          path: ${{ steps.rpm-output.outputs.path }}
